version: 2

python:
  install:
    - requirements: source/rtd_requirements.txt
    - method: pip
      path: .
sphinx: source/conf.py
configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3"
